import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import NavigationBar from '../components/NavigationBar/NavigationBar'
import './globals.css'
import { getDictionary } from '@/dictionaries/dictionaries'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: { lang: string }
}) {
  const dict = await getDictionary(params.lang);
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationBar
          lang={params.lang}
          dict={dict}
        />
        {children}
      </body>
    </html>
  )
}
